steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/nginx-php-app:latest'
      - '-f'
      - docker/nginx/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/nginx-php-app:latest'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/php-fpm-app:latest'
      - '-f'
      - docker/php/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/php-fpm-app:latest'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - nginx-php-app
      - '--image'
      - 'gcr.io/$PROJECT_ID/nginx-php-app:latest'
      - '--platform'
      - managed
      - '--region'
      - northamerica-northeast1
options:
  logging: CLOUD_LOGGING_ONLY
