steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/vusi-roofing-web/nginx:latest'
      - '-f'
      - docker/nginx/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/vusi-roofing-web/nginx:latest'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/vusi-roofing-web/php:latest'
      - '-f'
      - docker/php/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/vusi-roofing-web/php:latest'
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
   # Deploy using Docker Compose
  # -name: 'docker'
  #  args: ['run', '--rm', '-v', '/workspace:/app', 'gcr.io/cloud-builders/docker-compose', '-f', 'docker-compose.yaml', 'up', '-d']
  #  dir: '/workspace' 
  # - name: gcr.io/cloud-builders/gcloud
  #   args:
  #     - run
  #     - deploy
  #     - vusi-roofing-web
  #     - '--image'
  #     - 'gcr.io/$PROJECT_ID/vusi-roofing-web:latest'
  #     - '--platform'
  #     - managed
  #     - '--region'
  #     - northamerica-northeast1
options:
  logging: CLOUD_LOGGING_ONLY
