version: '3'

services:
  web:
    build:
      context: .
      dockerfile: gcr.io/vusi-roofing/vusi-roofing-web/php
      #dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    networks:
      - my_network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: gcr.io/vusi-roofing/vusi-roofing-web/nginx
      #dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
      - my_network

networks:
  my_network: